sudo: required

language: bash
services: docker

env:
- DOCKER_IMAGE=nginx

script:
- docker build -t ${DOCKER_IMAGE} .
- docker run -d -p 8080:80 -t ${DOCKER_IMAGE}

after_script:
- docker images | grep -q ${DOCKER_IMAGE}
- docker ps | grep -q ${DOCKER_IMAGE}